Add missing link libraries for Surface plugin
Add the internal library target libgwavi, as linking the plugin with the
'--no-undefined' linker flag reports undefined symbols:

/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld:
  CMakeFiles/Surfaces.dir/surfaces.cpp.o: in function
 `Avogadro::QtPlugins::Surfaces::recordMovie()':
  surfaces.cpp:(.text+0x2d2c):
undefined reference to `gwavi_open'

Also add AvogadroQtOpenGL, as it also required.

Fixes issue #436.