vtk: Add missing OpenGL link target
Without this, linking fails with

CMakeFiles/Vtk.dir/vtkAvogadroActor.cpp.o: in function `vtkAvogadroActor::RenderOpaqueGeometry(vtkViewport*)':
/usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:56:(.text+0x27a): undefined reference to `glGetFloatv'
/usr/bin/ld: /usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:57:(.text+0x28d): undefined reference to `glGetFloatv'
/usr/bin/ld: CMakeFiles/Vtk.dir/vtkAvogadroActor.cpp.o: in function `vtkAvogadroActor::RenderTranslucentPolygonalGeometry(vtkViewport*)':
/usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:74:(.text+0x4af): undefined reference to `glGetFloatv'
/usr/bin/ld: /usr/src/debug/avogadrolibs/avogadrolibs-1.98.0/avogadro/vtk/vtkAvogadroActor.cpp:75:(.text+0x4c2): undefined reference to `glGetFloatv'
collect2: error: ld returned 1 exit status

Signed-off-by: Antonio Rojas <arojas@archlinux.org>